### PR TITLE
Allow user to override the comment in the generated file

### PR DESCRIPTION
**Pull request by alexeagle**
Useful if they have some specific instructions to put there about how to update it

### CODE REVIEW

**Comment by zegl** [comment]
Hey Alex! Great change!

It looks like stardoc doesn't appreciate multiline default values 😕. I did some testing and it seems like wrapping `$attribute.defaultValue` in a call to `$util.markdownCellFormat()` will do the trick.

I'm OK with having a custom stardoc rule_template in this project if we need to, but it would be even better if we could get it upstreamed. :-)

**Comment by zegl** [comment]
Your change to remove the newline also makes sense, and might be even better.

**Comment by alexeagle** [comment]
Yeah I had to vendor the stardoc templates in rules_nodejs to fix a bunch of stuff :/
Doesn't seem like it's worth fighting with it? I hate to change the behavior of the rule just to make it user-controlled.

**Comment by alexeagle** [comment]
ping!

**Review by zegl — APPROVED** [review]
Thanks for the ping.

Yeah, it's annoying to have to remove the newline, but it's worth it IMO.

I'll get this change in.

**Pull request merged**
